# Generated by Django 4.1.3 on 2022-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.BigIntegerField()),
                ('title', models.CharField(default='Untitled', max_length=100, null=True)),
            ],
        ),
    ]
