# Generated by Django 4.1.3 on 2022-11-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bab',
            name='list_catatan',
        ),
        migrations.RemoveField(
            model_name='course',
            name='list_bab',
        ),
    ]
