# Generated by Django 4.1.3 on 2022-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_bab_list_catatan_remove_course_list_bab'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default='')),
                ('course_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bab',
            name='forum_id',
        ),
        migrations.RemoveField(
            model_name='bab',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='bab',
            name='bab_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bab',
            name='course_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DaftarCourse',
        ),
    ]
